# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['Client']

# %% ../nbs/00_core.ipynb 3
import pandas as pd

# %% ../nbs/00_core.ipynb 4
class Client:
    def __init__(self, token):
        self.token = token
        pass

    def load_csv(self, url):

        df = pd.read_csv(url, sep=',', header=0, index_col=0, encoding='utf-8')

        self.df = df

    def __repr__(self):
        return f'Client({self.name})'
